# Generated by Django 3.2 on 2021-04-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_rename_name_groupdata_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='user',
        ),
    ]
