# Generated by Django 3.2 on 2021-04-08 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_remove_studentdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.groupdata'),
        ),
    ]
